### ISSUE TITLE
500 Error when trying to Register from Olympus using wss port.

### ISSUE THREAD

**Issue by leftyb** [RestComm/load-balancer-docker#10]
Here the error:

getting 500 when trying to register with olympus.

[10:42] 
016-05-19 19:42:02,187 INFO SIP-TCP-Core-PipelineThreadpool-9 - Request not from server
2016-05-19 19:42:02,188 ERROR SIP-TCP-Core-PipelineThreadpool-9 - Unexpected exception while forwarding the request REGISTER sip:staging.restcomm.com SIP/2.0
Call-ID: 1463686922127
CSeq: 1 REGISTER
From: sip:lefty@staging.restcomm.com;tag=1463686922128
To: sip:lefty@staging.restcomm.com
Via: SIP/2.0/WSS 85.72.74.183:46700;branch=z9hG4bK-3537-f2f08f9644f68f0c6796030760ae3c70;rport=46700;received=85.72.74.183
Max-Forwards: 69
User-Agent: TelScale RTM Olympus/1.0.0
Expires: 3600
Allow: INVITE,ACK,CANCEL,BYE,OPTIONS,MESSAGE
Contact: sip:lefty@85.72.74.183:46700;transport=wss
X-Sip-Balancer-InitialRemoteAddr: 85.72.74.183
X-Sip-Balancer-InitialRemotePort: 46700
Route: sip:10.61.221.110:5083;transport=wss;lr
Content-Length: 0

javax.sip.InvalidArgumentException: Port value out of range -1, [1..65535]
       at gov.nist.javax.sip.header.Via.setPort(Via.java:315)
       at gov.nist.javax.sip.header.HeaderFactoryImpl.createViaHeader(HeaderFactoryImpl.java:1095)
       at org.mobicents.tools.sip.balancer.SIPBalancerForwarder.forwardRequest(SIPBalancerForwarder.java:1387)
       at org.mobicents.tools.sip.balancer.SIPBalancerForwarder.processRequest(SIPBalancerForwarder.java:902)
       at org.mobicents.tools.sip.balancer.SIPBalancerValveProcessor.processRequest(SIPBalancerValveProcessor.java:54)
       at gov.nist.javax.sip.stack.SIPTransactionStack.newSIPServerRequest(SIPTransactionStack.java:1487)
       at gov.nist.javax.sip.stack.ConnectionOrientedMessageChannel.processMessage(ConnectionOrientedMessageChannel.java:462)
       at gov.nist.javax.sip.stack.NioWebSocketMessageChannel.processMessage(NioWebSocketMessageChannel.java:323)
       at gov.nist.javax.sip.parser.NioPipelineParser$Dispatch.run(NioPipelineParser.java:189)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
       at java.lang.Thread.run(Thread.java:745)
2016-05-19 19:42:02,191 INFO SIP-TCP-Core-PipelineThreadpool-9 - <message
from="10.229.72.130:5063" 
to="85.72.74.183:46700" 
time="1463686922189"
isSender="true" 
transactionId="z9hg4bk-3537-f2f08f9644f68f0c6796030760ae3c70" 
callId="1463686922127" 
firstLine="SIP/2.0 500 Server Internal Error" 

> <![CDATA[SIP/2.0 500 Server Internal Error
> CSeq: 1 REGISTER
> Call-ID: 1463686922127
> From: sip:lefty@staging.restcomm.com;tag=1463686922128
> To: sip:lefty@staging.restcomm.com
> Via: SIP/2.0/WSS 85.72.74.183:46700;branch=z9hG4bK-3537-f2f08f9644f68f0c6796030760ae3c70;rport=46700;received=85.72.74.183
> Content-Length: 0

]]>
</message>

**Comment by leftyb** [comment]
Closing due to configuration error.
