### ISSUE TITLE
java.net.BindException: Cannot assign requested address (Bind failed)

### ISSUE THREAD

**Issue by gecock** [RestComm/load-balancer-docker#24]
### Summary
When using a custom configuration.xml file and supplying an ip address I get a binding error. I've ensured the port and address are correct and available.  I've also used the same configuration file with the non-docker 8.1.0 instance of the load balancer and it worked fine.

### Command: 
``` docker run --name=lb -v /root/Documents/SIP_Gateway/Telestax/docker:/opt/loadbalancer/config restcomm/load-balancer:latest ```

### Errors:
```
2017-01-24 14:46:30,831 ERROR main - Unexpected exception while starting the registry
java.lang.RuntimeException: Failed to bind due to:
        at org.mobicents.tools.sip.balancer.NodeRegisterImpl.register(NodeRegisterImpl.java:211)
        at org.mobicents.tools.sip.balancer.NodeRegisterImpl.startRegistry(NodeRegisterImpl.java:90)
        at org.mobicents.tools.sip.balancer.BalancerRunner.start(BalancerRunner.java:215)
        at org.mobicents.tools.sip.balancer.BalancerRunner.start(BalancerRunner.java:311)
        at org.mobicents.tools.sip.balancer.BalancerRunner.main(BalancerRunner.java:142)
Caused by: java.lang.RuntimeException: java.net.BindException: Cannot assign requested address (Bind failed)
        at org.mobicents.tools.sip.balancer.NodeRegisterImpl$BindingAddressCorrectnessSocketFactory.createServerSocket(NodeRegisterImpl.java:185)
        at sun.rmi.transport.tcp.TCPEndpoint.newServerSocket(TCPEndpoint.java:666)
        at sun.rmi.transport.tcp.TCPTransport.listen(TCPTransport.java:330)
        at sun.rmi.transport.tcp.TCPTransport.exportObject(TCPTransport.java:249)
        at sun.rmi.transport.tcp.TCPEndpoint.exportObject(TCPEndpoint.java:411)
        at sun.rmi.transport.LiveRef.exportObject(LiveRef.java:147)
        at sun.rmi.server.UnicastServerRef.exportObject(UnicastServerRef.java:234)
        at sun.rmi.registry.RegistryImpl.setup(RegistryImpl.java:195)
        at sun.rmi.registry.RegistryImpl.<init>(RegistryImpl.java:155)
        at java.rmi.registry.LocateRegistry.createRegistry(LocateRegistry.java:239)
        at org.mobicents.tools.sip.balancer.NodeRegisterImpl.register(NodeRegisterImpl.java:205)
        ... 4 more
Caused by: java.net.BindException: Cannot assign requested address (Bind failed)
        at java.net.PlainSocketImpl.socketBind(Native Method)
        at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:387)
        at java.net.ServerSocket.bind(ServerSocket.java:375)
        at java.net.ServerSocket.<init>(ServerSocket.java:237)
        at org.mobicents.tools.sip.balancer.NodeRegisterImpl$BindingAddressCorrectnessSocketFactory.createServerSocket(NodeRegisterImpl.java:182)
        ... 14 more
```

```
2017-01-24 14:46:31,206 ERROR main - Invalid argument address = X.XX.XX.XX port = 5061 transport = UDP
2017-01-24 14:46:31,206 ERROR main - An unexpected error occurred while starting the load balancer
java.lang.IllegalStateException: Can't create sip objects and lps due to[java.net.BindException: Cannot assign requested address (Bind failed)]
        at org.mobicents.tools.sip.balancer.SIPBalancerForwarder.start(SIPBalancerForwarder.java:207)
        at org.mobicents.tools.sip.balancer.BalancerRunner.start(BalancerRunner.java:241)
        at org.mobicents.tools.sip.balancer.BalancerRunner.start(BalancerRunner.java:311)
        at org.mobicents.tools.sip.balancer.BalancerRunner.main(BalancerRunner.java:142)
Caused by: javax.sip.InvalidArgumentException: java.net.BindException: Cannot assign requested address (Bind failed)
        at gov.nist.javax.sip.SipStackImpl.createListeningPoint(SipStackImpl.java:1642)
        at org.mobicents.tools.sip.balancer.SIPBalancerForwarder.createListeningPoints(SIPBalancerForwarder.java:2583)
        at org.mobicents.tools.sip.balancer.SIPBalancerForwarder.start(SIPBalancerForwarder.java:163)
        ... 3 more
Caused by: java.io.IOException: java.net.BindException: Cannot assign requested address (Bind failed)
        at gov.nist.javax.sip.stack.UDPMessageProcessor.<init>(UDPMessageProcessor.java:169)
        at gov.nist.javax.sip.stack.LoadBalancerUDPMessageProcessor.<init>(LoadBalancerUDPMessageProcessor.java:38)
        at gov.nist.javax.sip.stack.LoadBalancerNioMessageProcessorFactory.createMessageProcessor(LoadBalancerNioMessageProcessorFactory.java:46)
        at gov.nist.javax.sip.stack.SIPTransactionStack.createMessageProcessor(SIPTransactionStack.java:2502)
        at gov.nist.javax.sip.SipStackImpl.createListeningPoint(SipStackImpl.java:1617)
        ... 5 more
Caused by: java.net.BindException: Cannot assign requested address (Bind failed)
        at java.net.PlainDatagramSocketImpl.bind0(Native Method)
        at java.net.AbstractPlainDatagramSocketImpl.bind(AbstractPlainDatagramSocketImpl.java:93)
        at java.net.DatagramSocket.bind(DatagramSocket.java:392)
        at java.net.DatagramSocket.<init>(DatagramSocket.java:242)
        at java.net.DatagramSocket.<init>(DatagramSocket.java:299)
        at gov.nist.core.net.DefaultNetworkLayer.createDatagramSocket(DefaultNetworkLayer.java:98)
        at gov.nist.javax.sip.stack.UDPMessageProcessor.<init>(UDPMessageProcessor.java:144)
        ... 9 more
```

**Comment by croufay** [comment]
@gecock,

You might have an issue with the parameters used. This is how you would override a configuration file inside the docker container. 

docker run --name=lb -v /home/charles/telestax/lb-configuration.xml:/opt/loadbalancer/config/lb-configuration.properties restcomm/load-balancer:latest

Hope this helps


Charles

**Comment by gecock** [comment]
I tried using your command but the configuration wasn't changed from the default config.  Are you sure I should be mounting *.xml to *.properties? 

I then tried the following command replacing *.xml with *.xml and got the same error with binding.
`docker run --name=lb -v /root/Documents/SIP_Gateway/Telestax/docker/lb-configuration.xml:/opt/loadbalancer/config/lb-configuration.xml restcomm/load-balancer:latest`

**Comment by croufay** [comment]
@gecock ,

Sorry I missed your reply. Please do the following

sudo docker pull restcomm/load-balancer

Then, run the command like this. 

docker run --name=lb restcomm/load-balancer:latest


Regards



Charles 
Telestax

**Comment by gecock** [comment]
Right that works fine, but when I try to use my own configuration xml file to change the public IP address and udp port it does not work.

I'm going off the instructions in this repo's README
`2. attach volume with config: -v $PWD/config-lb-dir:/opt/loadbalancer/config`

I'm also going off the [documentation for configuring the LB](https://mobicents.ci.cloudbees.com/job/Restcomm-LoadBalancer/lastSuccessfulBuild/artifact/documentation/html-book/Load_Balancer_User_Guide.html#_sslb_configuring_the_sip_load_balancer_and_servlet_server_nodes)

**Comment by gecock** [comment]
This might be easier to reproduce. The same errors happen when I override the HOST_ADDRESS environment variable described in the README to the ip of the machine running the LB.

`docker run -e "HOST_ADDRESS=XXX.XXX.XXX.XXX" --name=lb restcomm/load-balancer:latest`

**Comment by bpulito** [comment]
I work with gecock. It looks like we should probably be configuring the externalIpLoadBalancerAddress instead of the host when running the SIP LB in a Docker container. We are trying this now. Does that make sense?

**Comment by deruelle** [comment]
@bpulito  @gecock if you want to run with the host address that is from the real host you need to start the command with --net=host ie 
`docker run -e "HOST_ADDRESS=192.168.0.44" --name=lb --net=host restcomm/load-balancer:latest`

**Comment by gecock** [comment]
That did it! Thanks @deruelle
